[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"
  NODE_ENV = "development"
  NPM_CONFIG_REGISTRY = "https://registry.npmjs.org/"
  NPM_FLAGS = "--registry=https://registry.npmjs.org/ --no-audit --no-fund --include=dev --legacy-peer-deps"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
